### ISSUE TITLE
Compilation failes every time

### ISSUE THREAD

**Issue by SterlingSilber** [Brumo21/AmongUsInternal#1]
Its not possible to compile, debug|32 and release|32 both fail with the standard repository, no changes made

**Comment by chubbynugly** [comment]
Same for me, 'cannot open input file 'libMinHook-x86-v141-mt.lib'

**Comment by chubbynugly** [comment]
actually after I fix that it just throws tons of errors

**Comment by Brumo21** [comment]
I apologize, the MinHook library has a .gitignore file within its folder that I didn't notice, therefore it was missing its lib folder. I fixed the problem, try compiling again, it should work.
